### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by GriffinMartin** [GriffinMartin/MI-449-SS17-740-js-intro-Vh2K33#1]
@chrisvfritz Can you take a look at this? It's [hosted here](https://GriffinMartin.github.io/MI-449-SS17-740-js-intro-Vh2K33/) and meets the following criteria:

- [x] At least 3 `button` elements are included in your page
- [x] When each of the buttons are hovered over (`mouseenter` event) or clicked on (`click` event), a unique sound effect plays from an `audio` element (try the `.play()` method) -- you may use [these drum kit sounds](/static/audio/drum-sounds.zip), create ones from [this sound effects generator](http://sfbgames.com/chiptone/), or use any other sounds that won't hurt/irritate the people who listen to them
- [x] Each button is well-labeled, corresponding to the sound it will play
- [x] All `audio` elements are invisible (no `controls` attribute), so that they can only be played with the buttons
- [x] All of your JavaScript is in a separate file ending with `.js`

**Comment by chrisvfritz** [comment]
![](https://i.imgur.com/xP0zu0U.jpg)

Lookin' good. 🤠  I'm going to give you a breakdown of the Good, the Bad, and the Ugly - spoiler: the Good definitely overwhelms everything else!

### The Good

- Even more than 3 sounds! 🔉💥 
- Well-styled! 💃 🕺 
- The `playSound` function very nicely reduces duplication here! 🛠 
- We were actually expecting `audio` elements because we didn't want to introduce the `new` keyword yet, but this is even better! 👾👨‍🚀 

### The Bad

- I think now that we have two JS files, we should do one of two things:
  - rename both to something more descriptive (e.g. `init-foundation.js` and `drum-machine.js`), OR
  - combine them into a single file

### The Ugly

- Even though the opening `<head>` and `<body>` tags don't have an empty line after them, the closing `</head>` and `</body>` tags do. An empty line there isn't necessarily bad, but for consistency, I would have an empty line in either both situations or neither.

---

If you have any questions/comments/etc, please don't hesitate to let me know. 😸  Otherwise, drop a comment here when those few areas for improvement have been addressed.

**Comment by GriffinMartin** [comment]
@chrisvfritz Thanks for the awesome feedback! I made the changes =)

**Comment by chrisvfritz** [comment]
Fantastic! :shipit: 🎉  

In GitHub comments, you can type an emoji by starting a word with a colon (`:`). Here's [a complete list](https://gist.github.com/rxaviers/7360908) of the emojis available. Also on macOS, `Cmd`+`Ctrl`+`Space` opens a little emoji search box. I'm actually not sure if there's something similar on Windows or Linux. 🙂
